services:
  postgres:
    image: postgres:15-alpine
    container_name: shopquiet-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0336433234'
      POSTGRES_DB: shopquiet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: shopquiet-redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: shopquiet-backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:0336433234@postgres:5432/shopquiet?schema=public
      - DIRECT_URL=postgresql://postgres:0336433234@postgres:5432/shopquiet?schema=public
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ZALO_APP_SECRET=hGNtMqkmTlK5lEXNY34d
      - ZALO_PAYMENT_PRIVATE_KEY=07c667ab71c5b3062e84e8332ff78021
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  zalo-mini-app:
    build:
      context: .
      dockerfile: apps/zalo-mini-app/Dockerfile
    container_name: shopquiet-zalo-mini-app
    ports:
      - '8080:80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

