services:
  - type: web
    name: shopquiet-backend
    env: node
    buildCommand: pnpm install && cd apps/backend && pnpm prisma db push && pnpm run build
    startCommand: cd apps/backend && pnpm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
