import type { ICartItem, INotification, IOrder, IProduct, IToastState, TToastType, IZaloUser } from '../../App.type';

export interface IAppState {
  cart: ICartItem[];
  activeTab: string;
  selectedProductDetail: IProduct | null;
  savedItems: IProduct[];
  isCartOpen: boolean;
  isChatOpen: boolean;
  chatContextProduct: IProduct | null;
  toast: IToastState | null;
  zaloUser: IZaloUser | null;
  selectedOrder: IOrder | null;
  buyNowItem: ICartItem | null;
  notifications: INotification[];
  toastTimerRef: ReturnType<typeof setTimeout> | null;
  viewedProducts: IProduct[];
  comparisonProducts: IProduct[];
  isComparisonOpen: boolean;

  setActiveTab: (tab: string) => void;
  setSelectedProductDetail: (product: IProduct | null) => void;
  setIsCartOpen: (open: boolean) => void;
  setIsChatOpen: (open: boolean) => void;
  setChatContextProduct: (product: IProduct | null) => void;
  setToast: (toast: IToastState | null) => void;
  showToast: (message: string, type?: TToastType) => void;
  updateZaloUser: (user: IZaloUser) => void;
  setSelectedOrder: (order: IOrder | null) => void;
  setBuyNowItem: (item: ICartItem | null) => void;
  addToCart: (product: IProduct, quantity?: number, size?: string, color?: string) => void;
  removeFromCart: (productId: number, size?: string, color?: string) => void;
  updateQuantity: (productId: number, qty: number, size?: string, color?: string) => void;
  clearCart: () => void;
  updateItemVariant: (productId: number, oldSize: string, newSize: string, oldColor: string, newColor: string) => void;
  toggleSavedItem: (product: IProduct) => void;
  isSavedItem: (productId: number) => boolean;
  syncUserFromStorage: (force?: boolean) => Promise<void>;
  refreshZaloProfile: () => Promise<void>;
  fetchFavorites: () => Promise<void>;
  fetchCart: () => Promise<void>;
  logout: () => Promise<void>;
  addToViewedProducts: (product: IProduct) => void;
  clearViewedProducts: () => void;
  addToComparison: (product: IProduct) => void;
  removeFromComparison: (productId: number) => void;
  clearComparison: () => void;
  gamificationData: any | null;
  fetchGamificationData: () => Promise<void>;
  claimDailyReward: () => Promise<void>;
  recommendations: IProduct[];
  fetchRecommendations: () => Promise<void>;
}
